# Generated by Django 5.2.4 on 2025-08-08 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0002_atividade_desempenho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='data_atividade',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='desempenho',
            name='atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desemprenhos', to='educacao.atividade'),
        ),
    ]
