# Generated by Django 5.2.4 on 2025-08-08 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0003_alter_atividade_data_atividade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desempenho',
            name='atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desempenhos', to='educacao.atividade'),
        ),
    ]
